# This is the basic transformer training setting with speaker embedding.
# This configuration reuqires 1 gpus in the case of each gpu memory = 12GB, and it takes 2~3 days.

# network architecture related
model-module: espnet.nets.pytorch_backend.e2e_ltt_transformer:Transformer
# embed-dim: 0
cdim: 510
eprenet-conv-layers: 5
eprenet-conv-filts: 3
eprenet-conv-chans: 64
adim: 256
aheads: 4
elayers: 4
eunits: 1024
dlayers: 4
dunits: 1024
use-weighted-masking: True
use-batch-norm: True
use-scaled-pos-enc: True
encoder-normalize-before: False
decoder-normalize-before: False
encoder-concat-after: False
decoder-concat-after: False
encoder-reduction-factor: 1
decoder-reduction-factor: 1
use-speaker-embedding: false
spk-embed-integration-type: add
use-image-input: true
image-height: 128
image-width: 256

transformer-input-layer: linear # conv2d-scaled-pos-enc

# minibatch related
batch-sort-key: input # shuffle or input or output
batch-size: 1
maxlen-in: 200
maxlen-out: 250
# batch-bins: 2500000   
                      # batch-size * (max_out * dim_out + max_in * dim_in)
                      # 5203 batches containing from 5 to 354 samples (avg 28 samples).

# training related
transformer-init: pytorch
transformer-warmup-steps: 4000
transformer-lr: 1.0
initial-encoder-alpha: 1.0
initial-decoder-alpha: 1.0
eprenet-dropout-rate: 0.0
transformer-enc-dropout-rate: 0.1
transformer-enc-positional-dropout-rate: 0.1
transformer-enc-attn-dropout-rate: 0.1
transformer-dec-dropout-rate: 0.1
transformer-dec-positional-dropout-rate: 0.1
transformer-dec-attn-dropout-rate: 0.1
transformer-enc-dec-attn-dropout-rate: 0.1

# optimization related
opt: noam
accum-grad: 16
grad-clip: 1.0
weight-decay: 0.0
patience: 0
epochs: 200 # 100 * 5,203 / 4 = 130,075 iters

# other
num-save-attention: 0
save-interval-epochs: 10
eval-interval-epochs: 10
